name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        shell: bash
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Start SSH agent and add key
        shell: bash
        env:
          SSH_PASS: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          # Start SSH agent
          eval "$(ssh-agent -s)"

          # Install expect first
          sudo apt-get update -q 
          sudo apt-get install -y expect

          # Create expect script
          tee add_key.exp << 'EOL'
          #!/usr/bin/expect
          set timeout 20
          spawn ssh-add ~/.ssh/id_rsa
          expect "Enter passphrase for"
          send "$env(SSH_PASS)\r"
          expect eof
          EOL

          # Set permissions and run
          chmod +x add_key.exp
          ./add_key.exp

      - name: Connect and pull
        shell: bash
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: Cleanup
        if: always()
        shell: bash
        run: rm -rf ~/.ssh add_key.exp
