name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SSH keys
        run: |
          # Create the .ssh directory with correct permissions
          install -m 700 -d ~/.ssh
          # Write the private key to the id_rsa file
          cat << 'EOF' > ~/.ssh/id_rsa
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          # Add the server to known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Start SSH agent and add key with passphrase
        run: |
          # Start the SSH agent (escape $ to prevent GitHub Actions from misinterpreting it)
          eval "$$(ssh-agent -s)"
          # Install expect to handle passphrase input
          sudo apt-get update
          sudo apt-get install -y expect
          # Use expect to provide the passphrase to ssh-add
          expect <<EOF
          spawn ssh-add ~/.ssh/id_rsa
          expect "Enter passphrase for ~/.ssh/id_rsa:"
          send "${{ secrets.SSH_PASSPHRASE }}\r"
          expect eof
          EOF
      
      - name: Connect and pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
      
      - name: Cleanup
        run: rm -rf ~/.ssh
