name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        shell: bash
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Start SSH agent and add key
        shell: bash
        run: |
          eval "$(ssh-agent -s)"
          # Create expect script file
          cat > add_key.exp << 'EOF'
          #!/usr/bin/expect -f
          spawn ssh-add ~/.ssh/id_rsa
          expect "Enter passphrase for /home/runner/.ssh/id_rsa:"
          send "$env(SSH_PASS)\n"
          expect eof
          EOF
          chmod +x add_key.exp
          
          # Install expect
          sudo apt-get update && sudo apt-get install -y expect
          
          # Run expect script with passphrase from secrets
          SSH_PASS=${{ secrets.SSH_PASSPHRASE }} ./add_key.exp

      - name: Connect and pull
        shell: bash
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: Cleanup
        if: always()
        shell: bash
        run: rm -rf ~/.ssh add_key.exp
