name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        shell: bash
        env:
          SSH_PASS: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          # Create .ssh directory with secure permissions
          install -m 700 -d ~/.ssh
          
          # Write private key file with secure permissions
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add server to known hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          # Start SSH agent
          eval "$(ssh-agent -s)"
          
          # Install expect package
          sudo apt-get update -q 
          sudo apt-get install -y expect -q
          
          # Create expect script
          tee add_key.exp << 'EOL'
          #!/usr/bin/expect
          set timeout 20
          spawn ssh-add ~/.ssh/id_rsa
          expect "Enter passphrase for"
          send "$env(SSH_PASS)\r"
          expect eof
          EOL
          
          # Set execute permissions and run expect script
          chmod +x add_key.exp
          ./add_key.exp
          
          # Run deployment command
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          rm -rf ~/.ssh add_key.exp
