name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        cat <<EOF > ~/.ssh/id_rsa
        ${{ secrets.SSH_PRIVATE_KEY }}
        EOF
        chmod 600 ~/.ssh/id_rsa

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install expect
      run: |
        sudo apt-get update
        sudo apt-get install -y expect

    - name: Start SSH Agent and Add Key with Passphrase
      run: |
        eval "$(ssh-agent -s)"
        expect -c "
        spawn ssh-add ~/.ssh/id_rsa
        expect \"Enter passphrase for ~/.ssh/id_rsa:\"
        send \"${{ secrets.SSH_PASSPHRASE }}\r\"
        expect eof
        "

    - name: Connect and pull
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

    - name: Cleanup
      run: rm -rf ~/.ssh
